"""Update user and category relationships.

Revision ID: 82a057b59829
Revises: b89639fd9c22
Create Date: 2025-10-08 01:08:25.237650

"""

# revision identifiers, used by Alembic.
revision = "82a057b59829"
down_revision = "b89639fd9c22"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
