"""Add expenses table.

Revision ID: b6edb7a186b8
Revises: 82a057b59829
Create Date: 2025-10-29 09:36:44.237809

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b6edb7a186b8"
down_revision = "82a057b59829"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Run the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "expenses",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("category_id", sa.UUID(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("expense_date", sa.Date(), nullable=False),
        sa.Column("is_recurring", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["expense_categories.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("dummy_model")
    op.drop_constraint(
        op.f("expense_categories_user_id_fkey"),
        "expense_categories",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "expense_categories",
        "user",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "expense_categories_user_id_fkey", "expense_categories", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("expense_categories_user_id_fkey"),
        "expense_categories",
        "user",
        ["user_id"],
        ["id"],
    )
    op.create_table(
        "dummy_model",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(length=200), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("dummy_model_pkey")),
    )
    op.drop_table("expenses")
    # ### end Alembic commands ###
